#pragma once

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.5.0
// Descriptor size: 39 (bytes)
// +----------+-------+-------------------+
// | ReportId | Kind  | ReportSizeInBytes |
// +----------+-------+-------------------+
// |        1 | Input |                 5 |
// +----------+-------+-------------------+
static const uint8_t hidReportDescriptor[] = 
{
    0x05, 0x0C,          // UsagePage(Consumer[0x000C])
    0x09, 0x01,          // UsageId(Consumer Control[0x0001])
    0xA1, 0x01,          // Collection(Application)
    0x85, 0x01,          //     ReportId(1)
    0x05, 0x20,          //     UsagePage(Sensors[0x0020])
    0x09, 0x27,          //     UsageId(Electrical: Potentiometer[0x0027])
    0xA1, 0x00,          //     Collection(Physical)
    0x05, 0x0C,          //         UsagePage(Consumer[0x000C])
    0x09, 0xE0,          //         UsageId(Volume[0x00E0])
    0x09, 0xE0,          //         UsageId(Volume[0x00E0])
    0x09, 0xE0,          //         UsageId(Volume[0x00E0])
    0x09, 0xE0,          //         UsageId(Volume[0x00E0])
    0x09, 0xE0,          //         UsageId(Volume[0x00E0])
    0x15, 0x00,          //         LogicalMinimum(0)
    0x26, 0xFF, 0x00,    //         LogicalMaximum(255)
    0x95, 0x05,          //         ReportCount(5)
    0x75, 0x08,          //         ReportSize(8)
    0x81, 0x02,          //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                //     EndCollection()
    0xC0,                // EndCollection()
};

#define DEEJ_VOLUME_ARRAY_ID (1)
struct DeejVolumeArray
{
    uint8_t ReportId = DEEJ_VOLUME_ARRAY_ID;
    uint8_t Payload[5];
} __attribute((packed));